name: Delete Vue ToDo Website

on: delete

jobs:
    delete:
      if: github.event.ref_type == 'branch'
      runs-on: ubuntu-latest
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
  
      steps:
        - name: Get branch name
          run: |
            branch_fullname=${{ github.event.ref }}
            branch_name=${branch_fullname#refs/heads/}
            echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV

        - name: Checkout Repository
          uses: actions/checkout@v3
  
        - name: Setup Node.js
          uses: actions/setup-node@v3
          with:
            node-version: 18
  
        - name: Delete CDK Infrastructure
          run: |
            cd backend
            npm ci
            npx cdk destroy --force